---
- hosts: localhost
  remote_user: root

  tasks:

    - name: clone churchtools repo
      git:
        repo=https://github.com/churchtools/churchtools_basic.git
        dest=/var/www/churchtools
        version=v2.56
      notify:
        - change churchtools permissions

    - name: create churchtools config
      template:
        src=templates/churchtools.config.j2
        dest=/var/www/churchtools/sites/default/churchtools.config

    - name: wait for the db container
      wait_for:
        host=db
        port=3306

    - name: churchtools db
      mysql_db:
        name=churchtools
        state=present
        login_host={{ lookup('env','DB_PORT_3306_TCP_ADDR') }}
        login_user=root
        login_password={{ lookup('env','DB_ENV_MYSQL_ROOT_PASSWORD') }}

  handlers:

    - name: change churchtools permissions
      command:
        chown -Rv www-data:www-data /var/www/churchtools
